Repository google/guava, pull requests merged in 2019-10, with the labels that each got.

#3629 Moe Sync
  android/pom.xml
  pom.xml
Labels: cla: yes, internal-sync

#3630 MOE sync
  android/guava-tests/test/com/google/common/net/MediaTypeTest.java
  android/guava/src/com/google/common/net/MediaType.java
  guava-gwt/test/com/google/common/net/MediaTypeTest_gwt.java
  guava-tests/test/com/google/common/net/MediaTypeTest.java
  guava/src/com/google/common/net/MediaType.java
Labels: cla: yes

#3634 Moe Sync
  android/guava/src/com/google/common/net/HttpHeaders.java
  guava/src/com/google/common/net/HttpHeaders.java
Labels: cla: yes, internal-sync

#3640 Moe Sync
  android/guava/src/com/google/common/primitives/Doubles.java
  android/guava/src/com/google/common/primitives/Floats.java
  android/guava/src/com/google/common/primitives/Ints.java
  android/guava/src/com/google/common/primitives/Longs.java
  guava/src/com/google/common/primitives/Doubles.java
  guava/src/com/google/common/primitives/Floats.java
  guava/src/com/google/common/primitives/Ints.java
  guava/src/com/google/common/primitives/Longs.java
Labels: cla: yes, internal-sync

#3644 Moe Sync
  android/guava/src/com/google/common/collect/EnumMultiset.java
  guava/src/com/google/common/collect/EnumMultiset.java
Labels: cla: no, internal-sync

#3648 Moe Sync
  android/guava-tests/test/com/google/common/graph/AbstractNetworkTest.java
  android/guava-tests/test/com/google/common/graph/ConfigurableSimpleDirectedSortedNetworkTest.java
  android/guava-tests/test/com/google/common/graph/ValueGraphTest.java
  android/guava/src/com/google/common/collect/AbstractMultiset.java
  android/guava/src/com/google/common/collect/HashBiMap.java
  android/guava/src/com/google/common/graph/MapIteratorCache.java
  android/guava/src/com/google/common/graph/MapRetrievalCache.java
  guava-tests/test/com/google/common/graph/AbstractNetworkTest.java
  guava-tests/test/com/google/common/graph/ConfigurableSimpleDirectedSortedNetworkTest.java
  guava-tests/test/com/google/common/graph/ValueGraphTest.java
  guava/src/com/google/common/collect/AbstractMultiset.java
  guava/src/com/google/common/collect/HashBiMap.java
  guava/src/com/google/common/graph/MapIteratorCache.java
  guava/src/com/google/common/graph/MapRetrievalCache.java
Labels: cla: yes, internal-sync

#3657 Moe Sync
  android/guava-tests/test/com/google/common/math/StatsAccumulatorTest.java
  android/guava-tests/test/com/google/common/math/StatsTest.java
  android/guava-tests/test/com/google/common/math/StatsTesting.java
  android/guava/src/com/google/common/math/Stats.java
  android/guava/src/com/google/common/math/StatsAccumulator.java
  guava-tests/test/com/google/common/math/StatsAccumulatorTest.java
  guava-tests/test/com/google/common/math/StatsTest.java
  guava-tests/test/com/google/common/math/StatsTesting.java
  guava/src/com/google/common/math/Stats.java
  guava/src/com/google/common/math/StatsAccumulator.java
Labels: cla: yes, internal-sync

#3658 Moe Sync
  android/guava/src/com/google/common/base/Converter.java
  guava/src/com/google/common/base/Converter.java
Labels: cla: yes, internal-sync

#3664 Moe Sync
  android/guava/src/com/google/common/io/ByteStreams.java
  guava/src/com/google/common/io/ByteStreams.java
Labels: cla: yes, internal-sync

#3675 MOE Sync 2019-10-29
  android/guava-tests/test/com/google/common/util/concurrent/AbstractFutureFallbackAtomicHelperTest.java
  android/guava-tests/test/com/google/common/util/concurrent/AbstractFutureTest.java
  android/guava-tests/test/com/google/common/util/concurrent/FuturesTest.java
  android/guava/src/com/google/common/util/concurrent/AbstractFuture.java
  android/guava/src/com/google/common/util/concurrent/AggregateFuture.java
  android/guava/src/com/google/common/util/concurrent/CombinedFuture.java
  guava-gwt/test/com/google/common/util/concurrent/FuturesTest_gwt.java
  guava-tests/test/com/google/common/util/concurrent/AbstractFutureFallbackAtomicHelperTest.java
  guava-tests/test/com/google/common/util/concurrent/AbstractFutureTest.java
  guava-tests/test/com/google/common/util/concurrent/FuturesTest.java
  guava/src/com/google/common/util/concurrent/AbstractFuture.java
  guava/src/com/google/common/util/concurrent/AggregateFuture.java
  guava/src/com/google/common/util/concurrent/CombinedFuture.java
Labels: cla: yes, internal-sync
