Repository google/guava, pull requests merged in 2020-02, with the labels that each got.

#3793 MOE Sync 2020-02-04
  android/guava/src/com/google/common/io/BaseEncoding.java
  guava/src/com/google/common/io/BaseEncoding.java
Labels: cla: yes, internal-sync

#3796 MOE Sync 2020-02-06
  android/guava/src/com/google/common/util/concurrent/AbstractFuture.java
  guava-tests/test/com/google/common/util/concurrent/AbstractFutureInnocuousThreadTest.java
  guava/src/com/google/common/util/concurrent/AbstractFuture.java
Labels: cla: no, internal-sync

#3797 MOE Sync 2020-02-10
  android/guava/src/com/google/common/collect/Table.java
  guava/src/com/google/common/collect/Table.java
Labels: cla: yes, internal-sync

#3778 Add more context to the guava.dev landing page
  index.md
Labels: cla: yes

#3799 MOE Sync 2020-02-12
  README.md
Labels: cla: yes, internal-sync

#3801 MOE Sync 2020-02-17
  android/guava-tests/test/com/google/common/graph/StandardImmutableDirectedGraphTest.java
  android/guava-tests/test/com/google/common/graph/StandardImmutableUndirectedGraphTest.java
  android/guava-tests/test/com/google/common/graph/StandardMutableDirectedGraphTest.java
  android/guava-tests/test/com/google/common/graph/StandardMutableUndirectedGraphTest.java
  android/guava-tests/test/com/google/common/graph/ValueGraphTest.java
  android/guava/src/com/google/common/graph/GraphBuilder.java
  android/guava/src/com/google/common/graph/ImmutableGraph.java
  android/guava/src/com/google/common/graph/ImmutableValueGraph.java
  android/guava/src/com/google/common/graph/StandardMutableGraph.java
  android/guava/src/com/google/common/graph/StandardMutableValueGraph.java
  android/guava/src/com/google/common/graph/StandardValueGraph.java
  android/guava/src/com/google/common/graph/ValueGraphBuilder.java
  guava-tests/test/com/google/common/graph/StandardImmutableDirectedGraphTest.java
  guava-tests/test/com/google/common/graph/StandardImmutableUndirectedGraphTest.java
  guava-tests/test/com/google/common/graph/StandardMutableDirectedGraphTest.java
  guava-tests/test/com/google/common/graph/StandardMutableUndirectedGraphTest.java
  guava-tests/test/com/google/common/graph/ValueGraphTest.java
  guava/src/com/google/common/graph/GraphBuilder.java
  guava/src/com/google/common/graph/ImmutableGraph.java
  guava/src/com/google/common/graph/ImmutableValueGraph.java
  guava/src/com/google/common/graph/StandardMutableGraph.java
  guava/src/com/google/common/graph/StandardMutableValueGraph.java
  guava/src/com/google/common/graph/StandardValueGraph.java
  guava/src/com/google/common/graph/ValueGraphBuilder.java
Labels: cla: yes, internal-sync

#3804 MOE Sync 2020-02-21
  android/guava-tests/test/com/google/common/collect/CompactHashMapTest.java
  android/guava-tests/test/com/google/common/collect/CompactLinkedHashMapTest.java
  android/guava/src/com/google/common/collect/CompactHashMap.java
  guava-tests/test/com/google/common/collect/CompactHashMapTest.java
  guava-tests/test/com/google/common/collect/CompactLinkedHashMapTest.java
  guava/src/com/google/common/collect/CompactHashMap.java
Labels: cla: yes, internal-sync

#3805 MOE Sync 2020-02-23
  android/guava-testlib/src/com/google/common/collect/testing/CollectionTestSuiteBuilder.java
  android/guava-testlib/src/com/google/common/collect/testing/Helpers.java
  android/guava-testlib/src/com/google/common/collect/testing/ListTestSuiteBuilder.java
  android/guava-testlib/src/com/google/common/collect/testing/SetTestSuiteBuilder.java
  android/guava-testlib/src/com/google/common/collect/testing/SortedSetTestSuiteBuilder.java
  android/guava-testlib/src/com/google/common/collect/testing/google/MultisetTestSuiteBuilder.java
  android/guava-testlib/src/com/google/common/collect/testing/google/SortedMultisetTestSuiteBuilder.java
  android/guava-testlib/src/com/google/common/testing/ClusterException.java
  android/guava-tests/test/com/google/common/collect/IteratorsTest.java
  guava-testlib/src/com/google/common/collect/testing/CollectionTestSuiteBuilder.java
  guava-testlib/src/com/google/common/collect/testing/Helpers.java
  guava-testlib/src/com/google/common/collect/testing/ListTestSuiteBuilder.java
  guava-testlib/src/com/google/common/collect/testing/SetTestSuiteBuilder.java
  guava-testlib/src/com/google/common/collect/testing/SortedSetTestSuiteBuilder.java
  guava-testlib/src/com/google/common/collect/testing/google/MultisetTestSuiteBuilder.java
  guava-testlib/src/com/google/common/collect/testing/google/SortedMultisetTestSuiteBuilder.java
  guava-testlib/src/com/google/common/testing/ClusterException.java
  guava-tests/test/com/google/common/collect/IteratorsTest.java
Labels: cla: yes, internal-sync

#3807 MOE Sync 2020-02-25
  android/guava-tests/test/com/google/common/graph/AbstractDirectedNetworkTest.java
  android/guava-tests/test/com/google/common/graph/AbstractNetworkTest.java
  android/guava-tests/test/com/google/common/graph/AbstractUndirectedNetworkTest.java
  android/guava-tests/test/com/google/common/graph/ConfigurableDirectedMultiNetworkTest.java
  android/guava-tests/test/com/google/common/graph/ConfigurableDirectedNetworkTest.java
  android/guava-tests/test/com/google/common/graph/ConfigurableSimpleDirectedNetworkTest.java
  android/guava-tests/test/com/google/common/graph/ConfigurableSimpleUndirectedNetworkTest.java
  android/guava-tests/test/com/google/common/graph/ConfigurableUndirectedMultiNetworkTest.java
  android/guava-tests/test/com/google/common/graph/ConfigurableUndirectedNetworkTest.java
  guava-tests/test/com/google/common/graph/AbstractDirectedNetworkTest.java
  guava-tests/test/com/google/common/graph/AbstractNetworkTest.java
  guava-tests/test/com/google/common/graph/AbstractUndirectedNetworkTest.java
  guava-tests/test/com/google/common/graph/ConfigurableDirectedMultiNetworkTest.java
  guava-tests/test/com/google/common/graph/ConfigurableDirectedNetworkTest.java
  guava-tests/test/com/google/common/graph/ConfigurableSimpleDirectedNetworkTest.java
  guava-tests/test/com/google/common/graph/ConfigurableSimpleUndirectedNetworkTest.java
  guava-tests/test/com/google/common/graph/ConfigurableUndirectedMultiNetworkTest.java
  guava-tests/test/com/google/common/graph/ConfigurableUndirectedNetworkTest.java
Labels: cla: yes, internal-sync
